baseUrl: https://q4.re/
languageCode: nl
title: Arne Govaerts
theme: quatre
enableRobotsTXT: true

author:
  name: Arne Govaerts
  email: arne@q4.re
  twitter: argovaerts
  github: argovaerts

outputs:
  home:
    - HTML
    - RSS
    - JSON
  page:
    - HTML
    - RSS

Params:
  description: Een random personal site
  license:
    name: CC BY-NC-SA 4.0
    url: https://creativecommons.org/licenses/by-nc-sa/4.0/
  menu:
    - name: home
      url: /
    - name: over
      url: /over
    - name: updates
      url: /updates
    - name: posts
      url: /posts
  endpoints:
    webmention: https://webmention.io/q4.re/webmention
    pingback: https://webmention.io/q4.re/xmlrpc
