baseUrl: https://q4.re/
languageCode: nl
title: Arne Govaerts
theme: quatre
enableRobotsTXT: true

author:
  name: Arne Govaerts
  email: arne@q4.re
  twitter: argovaerts
  github: argovaerts

Params:
  description: Een random personal site
  author:
    name: Arne Govaerts
    email: arne@q4.re
    twitter: argovaerts
    github: argovaerts
  license:
    name: CC BY-NC-SA 4.0
    url: https://creativecommons.org/licenses/by-nc-sa/4.0/
  menu:
    - name: home
      url: /
    - name: over
      url: /over
    - name: updates
      url: /updates
    - name: posts
      url: /posts
